import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next.js and must not be edited.
    ignores: [".next/**", "node_modules/**", "src/generated/**", "next-env.d.ts"],
  },
  {
    rules: {
      // Money must never be a JS number. See TECH_STACK.md 4B.
      "no-restricted-globals": [
        "error",
        { name: "parseFloat", message: "Use Decimal from decimal.js for monetary values." },
      ],
    },
  },
];

export default eslintConfig;
